struct Time
{
    long sec;
    unsigned long nanosec;
};

struct ParameterValue
{
    // Used to determine which of the next *_value fields are set.
    // ParameterType.PARAMETER_NOT_SET indicates that the parameter was not set
    // (if gotten) or is uninitialized.
    // Values are enumerated in `ParameterType.msg`.
    
    // The type of this parameter, which corresponds to the appropriate field below.
    octet type;
    
    // "Variant" style storage of the parameter value. Only the value corresponding
    // the type field will have valid information.
    
    // Boolean value, can be either true or false.
    boolean bool_value;
    
    // Integer value ranging from -9,223,372,036,854,775,808 to
    // 9,223,372,036,854,775,807.
    long long integer_value;
    
    // A double precision floating point value following IEEE 754.
    double double_value;
    
    // A textual value with no practical length limit.
    string string_value;
    
    // An array of bytes, used for non-textual information.
    sequence<octet> byte_array_value;
    
    // An array of boolean values.
    sequence<boolean> bool_array_value;
    
    // An array of 64-bit integer values.
    sequence<long long> integer_array_value;
    
    // An array of 64-bit floating point values.
    sequence<double> double_array_value;
    
    // An array of string values.
    sequence<string> string_array_value;
};

struct Parameter
{
    // The full name of the parameter
    string name;

    // The parameter's value which can be one of several types, see
    // `ParameterValue.msg` and `ParameterType.msg`.
    ParameterValue value;
};

struct ParameterEvent
{
    // The time stamp when this parameter event occurred.
    Time stamp;
    
    // Fully qualified ROS path to node.
    string node;
    
    // New parameters that have been set for this node.
    sequence<Parameter> new_parameters;
    
    // Parameters that have been changed during this event.
    sequence<Parameter> changed_parameters;
    
    // Parameters that have been deleted during this event.
    sequence<Parameter> deleted_parameters;
};
